import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import './fonts.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const integralCF = localFont({
  src: '../../public/fonts/IntegralCF-Bold.woff2',
  variable: '--font-integral-cf',
});

const satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/Satoshi-Regular.woff2',
      weight: '400',
    },
    {
      path: '../../public/fonts/Satoshi-Bold.woff2',
      weight: '700',
    }
  ],
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${integralCF.variable} ${satoshi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}